---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hugin-aggregator
  labels:
    app: hugin-aggregator
spec:
  selector:
    matchLabels:
      app: hugin-aggregator
  template:
    metadata:
      labels:
        app: hugin-aggregator
        tier: frontend
    spec:
      containers:
        - name: hugin-aggregator
          image: localhost:5000/hugin-aggregator
          imagePullPolicy: Always
          volumeMounts:
            - name: hugin-aggregator-config
              mountPath: /app/config
          ports:
            - containerPort: 3003
      volumes:
        - name: hugin-aggregator-config
          configMap:
            name: hugin-aggregator-config
---
apiVersion: v1
kind: Service
metadata:
  name: hugin-aggregator
spec:
  type: LoadBalancer
  selector:
    app: hugin-aggregator
    tier: frontend
  ports:
    - name: http
      protocol: TCP
      port: 3003
---
